[alembic]
# 迁移脚本的路径
script_location = migrations
# 数据库连接地址 (这里先写占位符，代码里会动态覆盖)
sqlalchemy.url = postgresql+asyncpg://qsandbox:qsandbox@localhost:5432/qsandbox

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S